### PR TITLE
Setup Intents Implemented + Card Reusablity Implemented

### PR DESCRIPTION
**Pull request by 0xamogh**

### CODE REVIEW

**Comment by 0xamogh** [comment]
Working on adding documentation and contributor table to the repo

**Comment by 0xamogh** [comment]
Android tasks are ✅ with this PR, solves #2 partially

**Comment by viktorasl** [comment]
Hey, thanks! It will take a while for the to look through as there are quite a lot of changes.
One think I notice is regarding code style, please keep it consistent (i.e always `) {` instead of `){` etc.). There are a few places where multiple newlines occur.

**Comment by 0xamogh** [comment]
Noted. Do you think its we could use eslint to autofix such issues?

**Comment by viktorasl** [comment]
> Noted. Do you think its we could use eslint to autofix such issues?

Sure!

**Comment by lukebrandonfarrell** [comment]
> Hey, thanks! It will take a while for the to look through as there are quite a lot of changes.
> One think I notice is regarding code style, please keep it consistent (i.e always `) {` instead of `){` etc.). There are a few places where multiple newlines occur.

Maybe we should add a code tool like prettier @viktorasl to pickup stuff like this

**Comment by viktorasl** [comment]
Either eslint or prettier. I don't have any preferences

**Comment by viktorasl** [comment]
Although both eslint and prettier work on js only, probably something like that is needed to be wrapped around native parts as well

**Comment by lukebrandonfarrell** [comment]
@viktorasl For sure, you have anything in mind?

**Comment by lukebrandonfarrell** [comment]
@amogh-jrules and @viktorasl  btw lets close this PR, we have both iOS and Android ready which can be PRd

**Comment by lukebrandonfarrell** [comment]
@amogh-jrules Let's close this PR and make a PR from our repo which covers both iOS and Android + add the contribution table.

**Pull request closed without merging**
